# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

definitions:
  workspace: &workspace
    docker:
      - image: circleci/node:15-browsers

    working_directory: ~/workspace

jobs:
  build-and-test:
    <<: *workspace

    steps:
      - checkout

      - run: sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update && sudo apt-get install build-essential gcc g++

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - persist_to_workspace:
          root: ~/workspace
          paths:
              - ./*

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test

